name: Reusable workflow example

# on:
#   workflow_call:
#     inputs:
#       spec:
#         required: true
#         type: string

# jobs:
#   example_job:
#     name: Test passing variables
#     runs-on: ubuntu-latest
#     steps:
#     - name: Test workflow
#       run: echo ${{ inputs.spec }}

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: First call
      run: echo test xyz 123
